/**
 * @file tpl_app_interrupts.c
 *
 * @section descr File description
 *
 * Generated functions related to interrupts.
 *
 * Generated from application blink
 * Automatically generated by goil on Www Mmm dd hh:mm:ss yyyy
 * from root OIL file main.oil
 *
 * @section infos File informations
 *
 */

#include "tpl_compiler.h"
#include "tpl_cortex_definitions.h"
#include "tpl_os_interrupt_kernel.h"
#include "cmsis_wrapper.h"


#define OS_START_SEC_CODE
#include "tpl_memmap.h"

/*=============================================================================
 * To disable the priority 6 interrupts, the corresponding ICER
 * are set
 */
FUNC(void, OS_CODE) tpl_disable_priority_6_interrupts(void)
{
  NVIC->ICER[0] = 0x40000000;
}

/*=============================================================================
 * To enable the priority 6 interrupts, the corresponding ISER
 * are set
 */
FUNC(void, OS_CODE) tpl_enable_priority_6_interrupts(void)
{
  NVIC->ISER[0] = 0x40000000;
}

/*=============================================================================
 * To disable the priority 7 interrupts, the corresponding ICER
 * are set
 */
FUNC(void, OS_CODE) tpl_disable_priority_7_interrupts(void)
{
  NVIC->ICER[0] = 0x40000001;
}

/*=============================================================================
 * To enable the priority 7 interrupts, the corresponding ISER
 * are set
 */
FUNC(void, OS_CODE) tpl_enable_priority_7_interrupts(void)
{
  NVIC->ISER[0] = 0x40000001;
}

#define OS_STOP_SEC_CODE
#include "tpl_memmap.h"

/*=============================================================================
 * Tables to access enable and disable functions according to the priority of
 * the ISR
 */
#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

CONST(tpl_enable_disable_func, OS_CONST) tpl_enable_table[2] = {
  tpl_enable_priority_6_interrupts,
  tpl_enable_priority_7_interrupts
};

CONST(tpl_enable_disable_func, OS_CONST) tpl_disable_table[2] = {
  tpl_disable_priority_6_interrupts,
  tpl_disable_priority_7_interrupts
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_START_SEC_CODE
#include "tpl_memmap.h"

/*=============================================================================
 * Initialize the priorities in the NVIC according to the priorities defined
 * in the OIL/ARXML file
 */
FUNC(void, OS_CODE) tpl_init_it_priority(void)
{
  /*
   * Init of ISR category 2 priorities
   */

  /* Init the priority of RTC_IRQ */
  NVIC_SetPriority(RTC_IRQ_Number, OS_ISR_PRIO_UNSHIFTED);
  /* Init the priority of DMA_IRQ */
  NVIC_SetPriority(DMA_IRQ_Number, OS_ISR_PRIO_UNSHIFTED);
}

/*=============================================================================
 * To disable the OS interrupts, the corresponding ICER
 * are set
 */
FUNC(void, OS_CODE) tpl_disable_os_interrupts(void)
{
  NVIC->ICER[0] = 0x40000001;
}

/*=============================================================================
 * To enable the OS interrupts, the corresponding ISER
 * are set
 */
FUNC(void, OS_CODE) tpl_enable_os_interrupts(void)
{
  NVIC->ISER[0] = 0x40000001;
}


#define OS_STOP_SEC_CODE
#include "tpl_memmap.h"

/* End of file tpl_app_interrupts.c */
